### PR TITLE
wallet connection improvements and fixes

### LINKED ISSUE #384: No RPC Url available for chainId: 42161 using `walletconnect`
Using `walletconnect` on arbitrum causing errors: No RPC Url available for chainId: 42161.

Context (in discord `help` channel): https://discord.com/channels/925416137225830450/925428183707287602/1013506343828725780

### PR DESCRIPTION
**Pull request by mds1**
Closes #384 

- [x] Upgrade to v2 of onboard.js
- [x] Configure it to support popular wallets
- [ ] Save most recently connected wallet to cache and try auto-connecting on page load
- [ ] Configure i18n support: https://docs.blocknative.com/onboard/core (cc @garyghayrat, would love if you could push a commit that implements this)
- [ ] Ensure we still refresh the page on wallet or network change
- [ ] Consider using the `accountCenter` feature to close https://github.com/ScopeLift/umbra-protocol/issues/315
- [ ] Cleanup unused imports, remove outdated/unused methods, fix any TS issues

Relevant docs: https://docs.blocknative.com/onboard

### CODE REVIEW

**Comment by mds1** [comment]
Assigned @alexkeating to #384 and he'll continue working on this PR

**Comment by alexkeating** [comment]
@mds1 @garyghayrat The i18n stuff looks easy to add once I have chinese copy. As far as I can tell it should be based on this file https://github.com/blocknative/web3-onboard/blob/v2-web3-onboard-develop/packages/core/src/i18n/en.json.

**Comment by garyghayrat** [comment]
> @mds1 @garyghayrat The i18n stuff looks easy to add once I have chinese copy. As far as I can tell it should be based on this file https://github.com/blocknative/web3-onboard/blob/v2-web3-onboard-develop/packages/core/src/i18n/en.json.

Hi Alex, just added the locale messages and the translations in our existing json files. https://github.com/ScopeLift/umbra-protocol/pull/387/commits/bd5b1421a47b81e8ebfe305341145489d65837b6

**Comment by alexkeating** [comment]
I looked into account center and it looks pretty difficult to customize at the moment. It would work probably best as a drop in replacement for the current connection button and avatar. But, I think any migration should be handled in #315 because it will require minimal changes to onboard and mostly require removing existing code.

**Comment by mds1** [comment]
Closing in favor of #395

**Pull request closed without merging**
