### PR TITLE
Set UmbraPaymaster trusted forwarder & redeploy Rinkeby

### PR DESCRIPTION
**Pull request by apbendi**

### CODE REVIEW

**Comment by mds1** [comment]
Can you run prettier on the JSON files? Otherwise looks good! cc @wildmolasses for more monorepo prettier config

**Comment by wildmolasses** [comment]
https://github.com/ScopeLift/umbra-protocol/blob/master/.lintstagedrc.js is the file to adjust!

**Comment by mds1** [comment]
Thanks Ed, just pushed a commit that should fix it!

**Review by mds1 — APPROVED** [review]

**Review by jferas — COMMENTED** [review]
LGTM!

**Pull request merged**
