### PR TITLE
Add faq

### PR DESCRIPTION
**Pull request by mds1**
Closes https://github.com/ScopeLift/umbra-protocol/issues/140

- Adds FAQ page (link in header). Each FAQ question and section header can be clicked to copy a URL to the clipboard. Navigating to the URL will open that FAQ question on page load
- Adds Terms of Service (link in footer). Don't love the location of the Terms of Service link so open to alternative locations for that link / alternative Footer layouts

### CODE REVIEW

**Review by apbendi — CHANGES_REQUESTED** [review]
Looks good, thanks for banging this out! A few things (and sorry in advance to nitpick on some of these!)

1. 
>  Each FAQ question and section header can be clicked to copy a URL to the clipboard. Navigating to the URL will open that FAQ question on page load

This sounds awesome, but doesn't seem to work for me. Clicking the headers does nothing. Clicking a question opens it, but does not change the URL or copy anything to the clipboard. Am I missing something? This is in Chrome, btw.

2. I sent the Privacy Policy separately, do you mind adding that as well?

3. Layout wise, here's a quick mockup of something that could possibly work a little better? I dunno, let me know what you think. Obviously it's done sloppily and not even properly aligned/centered, but I think you can see what I was going for.

Screen Shot 2021-04-20 at 7 31 14 AM

The RSS icon here is for a link to Umbra tagged ScopeLift blogposts, i.e. https://www.scopelift.co/blog/tag/umbra

I'd be ok with using something other than the RSS icon here (a generic web globe icon, for example? Or a document, or whatever makes sense). It was just an easy one to grab in the mockup tool.

The advanced mode toggle could live right about the horizontal divider line on the left. Or even better, I think putting that stuff up in the top right might be ideal. On my rather large 4K monitor, on slightly boomer-eyes resolution, those controls are well below the fold. For a lot of people, they might not see them. I'll leave it up to you whether it's worth moving, though.

**Comment by mds1** [comment]
> This sounds awesome, but doesn't seem to work for me. Clicking the headers does nothing. Clicking a question opens it, but does not change the URL or copy anything to the clipboard. Am I missing something? This is in Chrome, btw.

- When I float the mouse over a section header, a link icon shows up. Clicking copies the section URL to the clipboard and shows a success notification
- When I click a question, the section expands and it copies the header URL to the clipboard with no visual feedback (but maybe it should update the URL shown, hmm 🤔 )

Neither of these happen for you? I tested in Brave and Chrome and both work

> I sent the Privacy Policy separately, do you mind adding that as well?

Will do that now

> Layout wise...

I do like having the advanced in the footer to add friction to enabling it, since it can be risky and you really should know what you're doing. There's also the dark mode toggle, and those don't fit too well in the above mockup. It's also confusing whether the icons link to ScopeLift things or Umbra things. 

I think maybe 3 vertical columns would look good. Like a "Settings" column with the two toggles stacked vertically, an "About" column in the middle with links to ScopeLift, ToS, Privacy, then a "Links" column on the right for GitHub, Telegram, Twitter, etc. I'll search for some inspiration

**Comment by mds1** [comment]
I also just ran Prettier on the full repo, since there was on unformatted file (`Umbra.sol`)

**Comment by mds1** [comment]
Last todo before merging: Update URL when clicking a question

**Pull request merged**
