### PR TITLE
Ens subdomain registration

### LINKED ISSUE #155: ENS Subdomain Registration App Implementation
#### Contract Addresses:

* ENS Registry (mainnet & rinkeby): `0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e`
* Registrar:
  * rinkeby: `0xdADAfCFBcf0186D3682F0510d5588e02502b92d5`
  * mainnet: TBD
* Umbra Subdomain Resolver (i.e.`PublicStealthKeyResolver`)
  * rinkeby: `0xd96f1736333002EA76168f899DCa0a441846ea55`
  * mainnet: TBD

#### Process

1. Check if the user's selected subdomain is already owned by calling `owner(bytes32 node)` on the ENS Registry, where `node` is the namehash of the full domain, i.e. `namehash("matt.umbra.eth")`. If the return value is the zero address, the name is available and the user can continue to register. If it's anything else, the name is already taken and the user should be asked to pick a different name.
2. Register the name following the process below:

To register a new Umbra-ready subdomain for a user, call the following method on the Registrar:

```public
function register(
        bytes32 _label,
        address _owner,
        StealthKeyResolver _resolver,
        uint256 _spendingPubKeyPrefix,
        uint256 _spendingPubKey,
        uint256 _viewingPubKeyPrefix,
        uint256 _viewingPubKey
    )
```

Where:

* `_label` is the `sha3` hash of the sudomain string, i.e. for `matt.umbra.eth` it would be `sha3("matt")`
* `_owner` is the address of the user claiming the subdomain
* `_resolver` is the address of Umbra Subdomain Resolver
* Stealth key parameters are exactly what you'd expect

That's it! If the transaction succeeds, the user is now fully configured to use Umbra with their subdomain.

TBD: How to do "reverse resolution" for Umbra subdomains.

### PR DESCRIPTION
**Pull request by mds1**
Closes #155 

- Implements everything listed in #155
- Modifies the spec in #113: That issues mentions one "Umbra Resolver", but there are two: `PublicStealthKeyResolver` and `StealthKeyFIFSRegistrar`. The flow in #113 should now support both of those

Setup UX is currently subpar but will be resolved as part of #148

### CODE REVIEW

**Comment by apbendi** [comment]
@mds1 attempting to build this with `yarn` from the root directory results in the following error:

```
@umbra/umbra-js: $ tsc --build
@umbra/umbra-js: src/utils/cns.ts(7,33): error TS1261: Already included file name '/Users/bendi/Development/umbra/umbra-js/src/abi/CNSResolver.json' differs from file name '/Users/bendi/Development/umbra/umbra-js/src/abi/CnsResolver.json' only in casing.
@umbra/umbra-js: error Command failed with exit code 1.
```

**Comment by apbendi** [comment]
@mds1 After registering a subdomain (`ben.umbra.eth`) and setting up the stealth keys:

Screen Shot 2021-04-12 at 6 39 40 AM

I get the following error trying to send to it:

Screen Shot 2021-04-12 at 6 34 47 AM

**Comment by apbendi** [comment]
@mds1 just checked, and latest commit is f73daa08ab6c0f1b6f092a17392f7df75c90caa1, which looks right?

**Comment by mds1** [comment]
Oops, I was looking at the mainnet Registry, not Rinkeby. Your resolver is set and I was able to send you funds to ben.umbra.eth. You might need to just rebuild the umbra package then rebuild the app with `cd umbra-js && yarn build && cd ../frontend && yarn dev`

**Comment by apbendi** [comment]
Hey @mds1, ENS stuff is working now, thanks 👍 

That said, I'm seeing 3 E/CNS related test failures in the `umbra-js` tests.

**Comment by mds1** [comment]
Ah that was just because we use msolomon.eth for the tests, and I had changed my resolver back to the PublicResolver when testing. 

I just changed it back to ForwardingStealthKeyResolver, so tests should all pass now

**Pull request merged**
