### PR TITLE
fix from format in card

### LINKED ISSUE #232: Network Selector Never Loads When On Unsupported Network
If the user's wallet is on an unsupported network, the network selector no longer loads. Instead, the loading spinner continues forever. This appears to be a regression. In previous versions, the network selector would load and say "Unsupported Network", allowing the user to choose a valid network and switch. We should restore this functionality.

Screen Shot 2021-09-23 at 11 48 57 AM

### PR DESCRIPTION
**Pull request by radchukd**
Closes #232

### CODE REVIEW

**Review by mds1 — APPROVED** [review]

**Review by apbendi — CHANGES_REQUESTED** [review]
Hey @radchukd, looking good in terms of addresses with ENS names now showing in mobile mode 👍 

However, it looks like there's been a regression in the case of showing a normal address. It is no longer using the truncated form (i.e. 0x1234...5678), leading to normal addresses overflowing the screen in mobile:

Screen Shot 2021-09-23 at 11 56 44 AM

**Comment by radchukd** [comment]
Also fixes #232

**Comment by mds1** [comment]
Good catch @apbendi 

Changes look good, re-approved by me! Confirmed this fixes #232 also so @radchukd I edited your PR description so the issue will be linked and closed automatically once it's merged

**Review by apbendi — APPROVED** [review]
Working well. Thanks @radchukd 👏

**Pull request merged**
