### PR TITLE
More frontend updates

### PR DESCRIPTION
**Pull request by mds1**
Changes:

- Add interface for entering private key with placeholder explaining what will happen afterwards
- Add warning to header so users do not use accounts that hold funds on mainnet
- Add tutorial to home page explaining how to use the app
- Small change to login flow so you can navigate to pages without logging in first
- Cleanup CSS and improve mobile appearance

### CODE REVIEW

**Comment by mds1** [comment]
That is actually the first commit! Arguably that feature ("Handle entering private key") is still a WIP though because it doesn't actually do anything with the private key yet, since we just need the contract ready to do that. Let me know if you still think it should be changed

**Comment by apbendi** [comment]
> Arguably that feature ("Handle entering private key") is still a WIP though because it doesn't actually do anything with the private key yet, since we just need the contract ready to do that. Let me know if you still think it should be changed

Got it, this makes sense. In my head "WIP" basically means a commit that itself isn't completed. I would have worded what you're describing something like "Partial implementation of..." or "Initial implementation of..." 

I know this is super annoying, but do you mind rewording? 🙈🙈🙈 Maybe it's pure OCD brain but something about seeing "WIP" in a commit message makes it feel slipshod. (Although apparently I didn't notice one in the last PR so apparently I'm not paying very close attention 🤷‍♂️).

**Comment by mds1** [comment]
Ok, just reworded the commit message! Let me know how that looks.

**Comment by apbendi** [comment]
> Ok, just reworded the commit message! Let me know how that looks.

Well, actually, can you also change.....

Just kidding, looks great— sorry for being annoying!

**Pull request merged**
